task:
    name: builder
    timeout_in: 5h
    container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G 
      kvm: true
    run_script: # To sync sourcea
      - apt update && DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" apt-get install -y tzdata curl git sudo
      - bash <(curl https://raw.githubusercontent.com/Hellomaria9009/scripts/master/setup/android_build_env.sh)
      - git config --global user.name Your Name
      - git config --global user.email you@example.com
      - /usr/local/bin/repo init --depth=1 -u git://github.com/DotOS/manifest.git -b dot11 -g default,-device,-mips,-darwin,-notdefault
      - /usr/local/bin/repo sync -c -j8 --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
      - git clone https://github.com/Orangeskai/android_device_realme_RMX2001 -b DotOs --depth=1 device/realme/RMX2001
      - git clone https://github.com/Orangeskai/android_kernel_realme_RMX2001 -b DotOs --depth=1 kernel/realme/RMX2001
      - git clone https://github.com/Orangeskai/proprietary_vendor_realme -b Dotos --depth=1 vendor/realme
      - git clone https://github.com/Orangeskai/android_device_realme_mt6785-common -b lineage-18.1-plus --depth=1 device/realme/mt6785-common
      - source build/envsetup.sh
      - lunch dot_RMX2001-userdebug
      - make bacon -j8
      - up=out/target/product/RMX2001/*.zip
      - curl --upload-file $up https://transfer.sh/$($up); echo
