task:
    name: builder
    timeout_in: 5h
    container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G 
    run_script: # To sync source
      - apt update && DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" apt-get install -y tzdata
      - bash <(curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh)
      - git config --global user.name Your Name
      - git config --global user.email you@example.com
      
    run_setup: # To sync source
      - ~/bin/repo init --depth=1 -u git://github.com/DotOS/manifest.git -b dot11 -g default,-device,-mips,-darwin,-notdefault
      - ~/bin/repo sync -c -j7 --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
      - git clone https://github.com/Orangeskai/android_device_realme_RMX2001 -b DotOs --depth=1 device/realme/RMX2001
      - git clone https://github.com/Orangeskai/android_kernel_realme_RMX2001 -b DotOs --depth=1 kernel/realme/RMX2001
      - git clone https://github.com/Orangeskai/proprietary_vendor_realme -b Dotos --depth=1 vendor/realme
      - git clone https://github.com/Orangeskai/android_device_realme_mt6785-common -b lineage-18.1-plus --depth=1 device/realme/mt6785-common
      
    build_run:
      - source build/envsetup.sh
      - lunch dot_RMX2001-userdebug
      - make bacon -j$(nproc --all)
      - up=out/target/product/RMX2001/*.zip
      - curl --upload-file $up https://transfer.sh/$($up); echo
