task:
    name: builder
    timeout_in: 5h
    container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G 
    run_script: # To sync sourcea
      - apt update && DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" apt-get install -y tzdata curl git sudo
      - bash <(curl https://raw.githubusercontent.com/Hellomaria9009/scripts/master/setup/android_build_env.sh)
      - git config --global user.name Your Name
      - git config --global user.email you@example.com
      - /usr/local/bin/repo init --depth=1 -u https://github.com/PixelPlusUI-Elle/manifest -b eleven -g default,-device,-mips,-darwin,-notdefault
      - /usr/local/bin/repo sync -c -j8 --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
      - source build/envsetup.sh
      - lunch aosp_RMX2001-userdebug
      - mka bacon -j8
      - up=out/target/product/RMX2001/*.zip
      - curl --upload-file $up https://transfer.sh/$($up); echo
